on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Add New Issues to CVE Website Backlog Board
        uses: peter-evans/create-or-update-project-card@866533e2ae61f13c35fd1d374049713fab43c729 # current tag: v2
        with:
          project-name: https://github.com/orgs/CVEProject/projects/30
          column-name: Needs Triage
