on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Add New Issues to Backlog Board
        uses: peter-evans/create-or-update-project-card@866533e2ae61f13c35fd1d374049713fab43c729 # current tag: v2
        with:
          project-name: Backlog Board
          column-name: New Issues (Need to be Triaged)